include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Enforce strict code quality
    avoid_relative_lib_imports: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_types_on_closure_parameters: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true
    unnecessary_new: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    one_member_abstracts: true
    only_throw_errors: true
    package_api_docs: true
    prefer_asserts_in_initializer_lists: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: true
    prefer_final_fields: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    prefer_mixin: true
    prefer_null_aware_operators: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    type_annotate_public_apis: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true